Confirm to apply resources

diff --git a/bin/apply-yaml b/bin/apply-yaml
--- a/bin/apply-yaml
+++ b/bin/apply-yaml
@@ -16,6 +16,7 @@ if [ ! -z $1 ];then
     echo " "
     echo '   del-yaml --help' '              Show this help'
     echo " "
+    exit 0
   else
     dir=${1}
   fi
@@ -23,12 +24,21 @@ fi
 
 yaml_num=`ls -1 ${dir}/*.yaml 2>/dev/null|wc -l`
 if [ ${yaml_num} -gt 0 ];then
-  for i in `ls -1 ${dir}/*yaml`
-  do
-    ${k} apply -f ${i}
-  done
+  read -p "Are you sure you want to create all the resources defined by yaml files in the directory ${dir} (y/n)" yn
 else
   echo " "
   echo "No .yaml file in the directory: ${dir}"
   echo " "
+  exit 1
 fi
+
+case ${yn} in
+  [yY] ) for i in `ls -1 ${dir}/*.yaml`
+         do
+           ${k} apply -f ${i}
+         done
+      exit;;
+  [nN] ) echo " ";
+      exit;;
+  * ) echo "Invalid response.";;
+esac
